### PR TITLE
Edge supports `fetch` in stable now

### PR DESCRIPTION
**Pull request by abraham**
Ref: https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/14342/

### CODE REVIEW

**Comment by jakearchibald** [comment]
Ohhh, is this a standard user build or one of the insiders builds?

**Comment by abraham** [comment]
As I understand it this was included in the Anniversary update in August.

**Comment by jakearchibald** [comment]
Cool, I guess request & response is there too. Will update.

**Comment by alrra** [comment]
> Ohhh, is this a standard user build or one of the insiders builds?

@jakearchibald Yes, it's in the [stable builds](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/fetchapi/).

> As I understand it this was included in the Anniversary update in August.

@abraham That [is correct](https://github.com/MicrosoftEdge/Status/commit/848d79509cfbb27ed5bf57547b3e9c09949337bf).

**Comment by abraham** [comment]
@jakearchibald I added a commit marking Request/Response as supported as well.

**Comment by jakearchibald** [comment]
Brilliant, thank you!

**Pull request merged**
