### PR TITLE
Resources page additions/removals

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @jakearchibald 

A few updates to the Resources page, to add some newer libraries and remove some entries that are less relevant now.

### CODE REVIEW

**Comment by jakearchibald** [comment]
Cheers!

**Comment by jeffposnick** [comment]
Cool! Can you deploy to `gh-pages`?

**Comment by jakearchibald** [comment]
The build appears to be broken, looking into it

**Comment by jakearchibald** [comment]
Done!

**Pull request merged**
