### PR TITLE
IE -> Edge and Firefox update

### PR DESCRIPTION
**Pull request by karolklp**
@jakearchibald 
1) Edge
As promises - first requirement to SW will be introduced in edge, we can switch IE to Edge completely
2) Firefox - some updates

### CODE REVIEW

**Comment by jakearchibald** [comment]
Ohh, thanks for this, will review

**Comment by karolklp** [comment]
You can preview it https://karolklp.github.io/isserviceworkerready/build/ (I messed something up so it's in subdir :P)

**Comment by hsablonniere** [comment]
@karolklp I'm not so sure but I think you missed stuff at the end : `Request`, `Response`, `caches`...

**Comment by karolklp** [comment]
What do you mean? That FF supports them?

**Comment by hsablonniere** [comment]
Yes, I tested with a nightly `41.0a1 (2015-06-11)`

**Comment by jakearchibald** [comment]
Apologies for the delays looking into these, hopefully tomorrow

**Pull request merged**
