### PR TITLE
Update Edge data

### PR DESCRIPTION
**Pull request by rdeltour**
After @dstorey's [announcement on Twitter](https://twitter.com/dstorey/status/694961349445554176).

### CODE REVIEW

**Comment by jakearchibald** [comment]
Thank you!

**Comment by dstorey** [comment]
Note it is specifically Fetch that is **in** development. Service Workers, along with Push are high priority backlog. 

Promises should be updated, as they've been shipping in Edge for quite some time now.

**Comment by jakearchibald** [comment]
Will update it as soon as I can (PRs accepted too)

**Comment by jakearchibald** [comment]
Will merge this as soon as the CI passes, or will force it tomorrow morning.

**Comment by rdeltour** [comment]
> Will update it as soon as I can (PRs accepted too)

Let me know if you prefer that I update and squash this PR instead. But I'm unsure how the Fetch status has to spread over all the fetch-related sub items.
Also, since I looked it up: Promises are shipped since [build 10240](https://dev.windows.com/en-us/microsoft-edge/platform/status/promiseses6?filter=f3f0000bf&search=promis).

**Pull request merged**
